version: '2.1'

services:
  boxty-diary:
    build: .
    privileged: false
    restart: always
    ports:
      - "80:5000"
    environment:
      - SECRET_KEY
      - DATABASE_URL
      - FLASK_ENV
    volumes:
      - 'uploads-data:/app/app/static/uploads'
      - 'db-data:/app/instance'
    labels:
      io.balena.features.balena-socket: '1'

volumes:
  uploads-data:
  db-data:
